name: kuyacode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  kuyacode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /kuyacode') ||
      startsWith(github.event.comment.body, '/kuyacode')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run kuyacode
        uses: anomalyco/kuyacode/github@latest
        env:
          KUYACODE_API_KEY: ${{ secrets.KUYACODE_API_KEY }}
          KUYACODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: kuyacode/claude-opus-4-5
